### ISSUE TITLE
Enhancement: Link previews for a search result

### ISSUE THREAD

**Issue by zsisco** [ucsb-cs56-f19/mapache-search#37]
We want to a feature on the search results page that lets a user click a "preview" button and see a rendered preview of that web page.

**Comment by btk5h** [comment]
I gave this a shot and arrived at the conclusion that generalized link previewing is infeasible. 

The root issue comes from the fact that many websites (such as Stack Overflow) have a Content Security Policy that prevent their site from being embedded in an `iframe` or `embed` tag.

We can get around this issue by creating some sort of `ProxyController` class that  simply fetches content from a url on the user's behalf and serves it under our origin. This allows us to use our own frame policy instead of the original site policy. This (combined with a `sandbox="allow-scripts"` attribute on the iframe to circumvent [frame-buster code](https://en.wikipedia.org/wiki/Framekiller)) *almost* works perfectly, until you click on a link on the page.

Clicking on a link does one of two things:

1. It will redirect you to another site (thus running into the original CSP issue)
2. It will redirect you to a page relative to the web app (which is incorrect, we want it relative to the site that we're embedding)

Now, there are totally workarounds for this. If this feature was essential, we could quickly hack it in by injecting some javascript that rewrites all of the links on the page. Unfortunately, if you haven't noticed already, the implementation for that would be ridiculous. It would be messy, prone to breaking, and annoying to maintain (especially considering what our current tech stack is).

The moral of the story: let's just respect that some sites just don't want to be embedded in iframes.

**Comment by btk5h** [comment]
Closing this in favor of #38, which is a far more reasonable implementation of this.
