### ISSUE TITLE
put the search results in rating order

### ISSUE THREAD

**Issue by darraghjburke** [ucsb-cs56-f19/mapache-search#59]

**Comment by btk5h** [comment]
Interesting implementation issue: what happens if a highly rated search result isn't on the first page?

If we only make one API call, we will only have access to the results on a single page. We might not necessarily want to make multiple API calls since that would count against the daily limit.

Whoever starts on this issue will have to decide whether it's acceptable just to sort the results on a single page (instead of taking all 100 results into consideration).
